name: Deploy to EC2

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    environment: PRD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 \
            | docker login --username AWS --password-stdin 138654649620.dkr.ecr.us-east-1.amazonaws.com

      - name: Build, tag, and push image to ECR
        run: |
          docker build -t 138654649620.dkr.ecr.us-east-1.amazonaws.com/wbmagalhaes:latest .
          docker push 138654649620.dkr.ecr.us-east-1.amazonaws.com/wbmagalhaes:latest

      - name: Deploy via SSM
        run: |
          aws ssm send-command \
            --targets "Key=InstanceIds,Values=${{ secrets.AWS_EC2_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy Go app + Redis" \
            --parameters 'commands=[
              "cd /home/ubuntu/app",
              "docker-compose pull",
              "docker-compose down",
              "docker-compose up -d"
            ]'
